version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@2.0.3


jobs:
  example-job:
    docker:
      - image: cimg/base:stable
    working_directory: ~/test
    steps:
      - aws-cli/setup:
          profile-name: circleci 
      - checkout
      - run:
          name: install dependencies
          command: |
            aws configure
            aws lightsail get-instances
#            sudo apt-get install npm
#            npm install

workflows:
  example-workflow:
    jobs:
      - example-job
