version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  example-job:
    executor: aws-cli/default
    working_directory: ~/test
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: circleci 
      - run:
          name: install dependencies
          command: |
             aws lightsail download-default-key-pair > t.pem
             ls
#            aws lightsail get-instances
#            sudo apt-get install npm
#            npm install

workflows:
  example-workflow:
    jobs:
      - example-job
